from fastapi import APIRouter, Depends, HTTPException
from loguru import logger
from sqlalchemy import select

from server.config import EXAMPLE_USER_USERNAME, GUEST_USER_USERNAME
from server.lib.AuthUtils import get_current_user
from server.lib.DataManager import DataManager
from server.models.data_view import DataRef, DataView
from server.models.database import (
    AsyncSession,
    NodeOutputRecord,
    ProjectRecord,
    UserRecord,
    get_async_session,
)

router = APIRouter()

@router.get(
    "/{data_id}",
    status_code=200,
    responses={
        200: {"description": "Data retrieved successfully", "model": DataView},
        404: {"description": "Project or Data not found"},
        403: {"description": "User has no access to this data"},
        500: {"description": "Internal server error"},
    },
)
async def get_node_data(
    data_id: int, 
    db_client: AsyncSession = Depends(get_async_session),
    user_record: UserRecord = Depends(get_current_user),
) -> DataView:
    """
    Get the data generated by a node.
    """
    user_id = int(user_record.id) # type: ignore
    data_manager = DataManager(async_db_session=db_client)
    try:
        # 1. get data row from db
        data_record = await db_client.get(NodeOutputRecord, data_id)
        if data_record is None:
            raise HTTPException(status_code=404, detail="Data not found")
        # 2. check user access right here
        db_project = await db_client.get(ProjectRecord, data_record.project_id)
        if db_project is None:
            raise HTTPException(status_code=404, detail="Project not found")
        if db_project.owner_id != user_id:  # type: ignore
            if db_project.show_in_explore is False:
                raise HTTPException(
                    status_code=403, detail="User has no access to this data"
                )
        # 3. get data view and return
        data = await data_manager.read_async(data_ref = DataRef(data_id=data_id))
        return data.to_view()
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"Error retrieving node data {data_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get(
    "/guest/{data_id}",
    status_code=200,
    responses={
        200: {"description": "Data retrieved successfully", "model": DataView},
        404: {"description": "Project or Data not found"},
        403: {"description": "User has no access to this data"},
        500: {"description": "Internal server error"},
    },
)
async def get_node_data_guest(
    data_id: int,
    db_client: AsyncSession = Depends(get_async_session),
) -> DataView:
    """
    Get the data generated by a node.
    """
    data_manager = DataManager(async_db_session=db_client)
    try:
        # 1. get data row from db
        data_record = await db_client.get(NodeOutputRecord, data_id)
        if data_record is None:
            raise HTTPException(status_code=404, detail="Data not found")
        # 2. check user access right here
        db_project = await db_client.get(ProjectRecord, data_record.project_id)
        if db_project is None:
            raise HTTPException(status_code=404, detail="Project not found")
        guest_rcd = await db_client.execute(
            select(UserRecord)
            .where(UserRecord.username == GUEST_USER_USERNAME)
        )
        quest_rcd = guest_rcd.scalar_one_or_none()
        if quest_rcd is None:
            raise HTTPException(status_code=404, detail="Guest user not found")
        example_rcd = await db_client.execute(
            select(UserRecord)
            .where(UserRecord.username == EXAMPLE_USER_USERNAME)
        )
        example_rcd = example_rcd.scalar_one_or_none()
        if example_rcd is None:
            raise HTTPException(status_code=404, detail="Example user not found")
        if db_project.owner_id != quest_rcd.id and db_project.owner_id != example_rcd.id:  # type: ignore
            raise HTTPException(status_code=403, detail="User has no access to this data")
        # 3. get data view and return
        data = await data_manager.read_async(data_ref=DataRef(data_id=data_id))
        return data.to_view()
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"Error retrieving node data {data_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
